#!/bin/sh

docker run -d\
           --name graphite\
           --restart=always\
           -p 80:80\
           -p 2003-2004:2003-2004\
           -p 2023-2024:2023-2024\
           graphiteapp/graphite-statsd